// File generated by Antigravity - manual configuration from native files.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are entering a missing configuration area.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you are entering a missing configuration area.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you are entering a missing configuration area.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you are entering a missing configuration area.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5uZcb9are_ySppDkGbJU28LprsHcqUw',
    appId: '1:636178650187:android:fbd04cbf29a01c4f8ba9ce',
    messagingSenderId: '636178650187',
    projectId: 'clinic-audio-app',
    storageBucket: 'clinic-audio-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8WS5ywG3I3IIntD_uzHsrXiZjv1l9tug',
    appId: '1:636178650187:ios:f94f018808fe690e8ba9ce',
    messagingSenderId: '636178650187',
    projectId: 'clinic-audio-app',
    storageBucket: 'clinic-audio-app.appspot.com',
    iosBundleId: 'com.infinitywellness.clinicaudioapp',
  );
}
